cst = {
'cats':{
    0:"Uncategorized",
    1:"Establishing why your topic X is important",
    2:"Outlining the past-present history of the study of X",
    3:"Outlining the possible future of X",
    4:"Indicating the gap in knowledge and possible limitations",
    5:"Stating the aim of your paper and its contribution",
    6:"Explaining the key terminology in your field",
    7:"Explaining how you will use terminology and acronyms in your paper",
    8:"Giving the structure of paper - what is and is not included",
    9:"Giving general panorama of past-to-present literature",
    10:"Reviewing past literature",
    11:"Reviewing subsequent and more recent literature",
    12:"Reporting what specific authors have said",
    13:"Mentioning positive aspects of others’ work",
    14:"Highlighting limitations of previous studies - authors not mentioned by name",
    15:"Highlighting limitations of previous studies - authors mentioned by name",
    16:"Using the opinions of others to justify your criticism of someone’s work",
    17:"Describing purpose of testing / methods used",
    18:"Outlining similarities with other authors’ models, systems etc.",
    19:"Describing the apparatus and materials used and their source",
    20:"Reporting software used",
    21:"Reporting customizations performed",
    22:"Formulating equations, theories and theorems",
    23:"Explaining why you chose your specific method, model, equipment, sample etc.",
    24:"Explaining the preparation of samples, solutions etc.",
    25:"Outlining selection procedure for samples, surveys etc.",
    26:"Indicating the time frame (past tenses)",
    27:"Indicating the time frame in a general process (present tenses)",
    28:"Indicating that care must be taken",
    29:"Describing benefits of your method, equipment etc.",
    30:"Outlining alternative approaches",
    31:"Explaining how you got your results",
    32:"Reporting results from questionnaires and interviews",
    33:"Stating what you found",
    34:"Stating what you did not find",
    35:"Highlighting significant results and achievements",
    36:"Stating that your results confirm previous evidence",
    37:"Stating that your results are in contrast with previous evidence",
    38:"Stating and justifying the acceptability of your results",
    39:"Expressing caution regarding the interpretation of results",
    40:"Outlining undesired or unexpected results",
    41:"Admitting limitations",
    42:"Explaining and justifying undesired or unexpected results",
    43:"Minimizing undesired or unexpected results",
    44:"Expressing opinions and probabilities",
    45:"Announcing your conclusions and summarizing content",
    46:"Restating the results (Conclusions section)",
    47:"Highlighting achievements (Conclusions section)",
    48:"Highlighting limitations (Conclusions section)",
    49:"Outlining possible applications and implications of your work",
    50:"Future work already underway or planned by the authors",
    51:"Future work proposed for third parties to carry out",
    52:"Acknowledgements",
    53:"Referring to tables and figures, and to their implications",
    54:"Making transitions, focusing on a new topic",
    55:"Referring backwards and forwards in the paper",
    56:"Referring back to your research aim",
    57:"Referring outside the paper",
},
'secs':{
    0: "Abstraction",
    1: "Introduction",
    2: "Previous Work",
    3: "Theory",
    4: "Dataset",
    5: "Experitment",
    6: "Conclusion",
    7: "Acknowledgement",
},
'tags':{
    0: "reason",
    1: "part",
    2: "type",
    3: "statement",
    4: "pos",
    5: "?",
    6: "+",
}
}